# Generated by Django 4.2.16 on 2024-12-07 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mov_category', '0002_movcategory_second_catg'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementData',
            fields=[
                ('mov_id', models.AutoField(primary_key=True, serialize=False)),
                ('mov_period', models.CharField(max_length=7)),
                ('mov_value', models.CharField(max_length=150)),
                ('mov_date', models.CharField(max_length=10)),
                ('mov_description', models.CharField(blank=True, max_length=200)),
                ('period_is_open', models.CharField(default='Y', max_length=1)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('mov_catg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_catg_ids2', to='mov_category.movcategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ids2', to='login.userdata')),
            ],
        ),
    ]
