# Generated by Django 4.2.16 on 2024-12-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementdata',
            name='last_update_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
