# Generated by Django 4.2.16 on 2024-10-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovCategory',
            fields=[
                ('mov_catg_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_category', models.CharField(max_length=30)),
                ('category_name', models.CharField(max_length=30)),
                ('category_description', models.CharField(blank=True, max_length=80)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.CharField(blank=True, default='P', max_length=50)),
            ],
        ),
    ]
