# Generated by Django 4.2.16 on 2024-10-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movcategory',
            name='second_catg',
            field=models.CharField(default='P', max_length=30),
            preserve_default=False,
        ),
    ]
