# Generated by Django 4.2.16 on 2025-06-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('mov_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('budget_period', models.CharField(max_length=7)),
                ('budget_value', models.CharField(max_length=150)),
                ('budget_description', models.CharField(blank=True, max_length=200)),
                ('period_is_open', models.CharField(default='No', max_length=2)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('close_per_date', models.CharField(blank=True, max_length=10)),
                ('mov_catg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_catg_ids', to='mov_category.movcategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ids', to='login.userdata')),
            ],
        ),
    ]
