# Generated by Django 4.2.16 on 2024-10-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetdata',
            old_name='period_status',
            new_name='period_is_open',
        ),
    ]
