# Generated by Django 4.2.16 on 2025-01-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_data', '0002_rename_period_status_budgetdata_period_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdata',
            name='close_per_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
